server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: DrunkDoge19356@
    url: jdbc:mysql://localhost:3306/chess
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-dll: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: testkekwwtf@gmail.com
    password: kosxkqjfrwtgzchb

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

